name: snowpark
channels:
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.8.16
  - pip:
      - snowflake-snowpark-python==1.4.0
      - Pillow==9.5.0
      - streamlit==1.22.0
      - stripe==5.4.0
